#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#Meus alias#
alias gcc='gcc -ansi -pedantic -Wall -lm -std=c99'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'

# Pequeno código que testa arquivos e compila o programa
test() {
	baseDir=${PWD##*/}
	for file in ../tests/arq*.in; do
		baseFile=$(basename $file ".in")
		inFile="$baseFile.in"
		outFile="$baseFile.out"
		resFile="$baseFile.res"
		testId=$(echo $baseFile | grep -Po '(?<=arq).*');

		echo "Test $testId";

		"./$baseDir" < "../tests/$inFile" > "../tests/$outFile"
		diff "../tests/$outFile" "../tests/$resFile"
	done
}

compile() {
	gcc *.c -o "${PWD##*/}"
}

# Quando usamos "seta para cima" para visualizar o historico de
# comandos, essa especificacao faz com que comandos iguais sejam
# ignorados
HISTCONTROL=ignoreboth
export HISTCONTROL
